name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test-action
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Deno Deploy
        uses: ./
        with:
          project: happy-rat-64
          root: action/tests
          entrypoint: hello.ts
          import-map: ./import_map.json
      - name: Deploy with single include
        uses: ./
        with:
          project: happy-rat-64
          root: action/tests
          entrypoint: include_exclude.ts
          include: include_exclude.ts
      - name: Deploy with comma-separated exclude 
        uses: ./
        with:
          project: happy-rat-64
          root: action/tests
          entrypoint: include_exclude.ts
          exclude: import_bomb1.ts, import_bomb2.ts
      - name: Deploy with multiline exclude 
        uses: ./
        with:
          project: happy-rat-64
          root: action/tests
          entrypoint: include_exclude.ts
          exclude: |
            import_bomb1.ts
            import_bomb2.ts
